services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: hmvc-backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    ports:
      - "8000:80"

  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: hmvc-frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
