services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: hmvc-backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: sh -c "composer install && php-fpm"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/node/Dockerfile
    container_name: hmvc-frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: hmvc-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge